# Generated by Django 2.2.6 on 2019-10-20 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circuito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Temperatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datahora', models.DateTimeField(auto_now_add=True)),
                ('temperatura', models.FloatField()),
                ('degelo', models.BooleanField(default=False)),
                ('circuito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Circuito')),
            ],
        ),
    ]
