# Generated by Django 2.2.6 on 2019-10-20 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperatura',
            name='id_email',
            field=models.IntegerField(default=0),
        ),
    ]
