# Generated by Django 2.2.6 on 2019-10-20 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_temperatura_id_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperatura',
            name='arquivo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
