# Generated by Django 2.2.6 on 2019-10-21 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_temperatura_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuito',
            name='posicao_coluna',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
