# Generated by Django 2.2.6 on 2019-10-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191022_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuito',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
