# Generated by Django 2.2.6 on 2019-10-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191022_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperatura',
            name='datahora',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
