# Generated by Django 2.2.6 on 2019-10-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191022_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='conformidade',
            name='faixa1',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
