# Generated by Django 2.2.6 on 2019-10-22 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_conformidade_faixa1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conformidade',
            name='faixa1',
        ),
    ]
