# Generated by Django 2.2.6 on 2019-10-22 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_conformidade_faixa1'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuito',
            name='faixa1',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
