# Generated by Django 2.2.6 on 2019-10-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_circuito_faixa1'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuito',
            name='tempo_degelo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
