# Generated by Django 2.2.6 on 2019-10-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_circuito_tempo_degelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuito',
            name='faixa2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='circuito',
            name='faixa3',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='circuito',
            name='faixa4',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='circuito',
            name='faixa5',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='circuito',
            name='faixa6',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='circuito',
            name='faixa7',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='circuito',
            name='faixa8',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
