# Generated by Django 2.2.6 on 2020-01-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200108_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgrupamentoCircuitos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='temperatura',
            name='degelo',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
