# Generated by Django 2.2.6 on 2020-01-08 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200108_1818'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgrupamentoCircuitos',
        ),
    ]
